import { useState } from "react";
import { Appear } from "arwes";
import { useMission } from "../context/MissionContext";
import "./Tracking.css";
import "./SatelliteLayout.css";
import "./ScienceCapture.css";
import "./ScienceImageAssets.css";
import "./RealisticMap.css";

const roverEvents = [
  ["14:32:25", "Rover moving", "ACT"], ["14:32:19", "Route updated", "REPLAN"], ["14:32:16", "Target detected", "SENSE"], ["14:32:12", "Terrain scanned", "ANALYSE"], ["14:32:08", "Position updated", "MONITOR"],
];

const satelliteEvents = [
  ["09:18:42", "Priority telemetry transmitted", "TELEMETRY"], ["09:18:31", "Orbit state updated", "MONITOR"], ["09:18:16", "Science observation queued", "DECIDE"], ["09:17:58", "Thermal scan nominal", "SENSE"], ["09:17:40", "Ground link established", "ACT"],
];

const scienceFrames = [
  ["/img/images.jpg", "IMG_001.jpg", "Panoramic View"], ["/img/images%20(1).jpg", "IMG_002.jpg", "Rock Sample (Close-up)"], ["/img/images%20(2).jpg", "IMG_003.jpg", "Surface Texture"],
  ["/img/images%20(3).jpg", "IMG_004.jpg", "Stratification"], ["/img/images%20(4).jpg", "IMG_005.jpg", "Horizon View"], ["/img/images%20(5).jpg", "IMG_006.jpg", "Target Context"],
];

const RoverVisual = ({ progress }) => <svg className="tracking-svg" viewBox="0 0 760 410" role="img" aria-label="Simulated AMINA rover moving across a terrain map"><defs><pattern id="rover-grid" width="38" height="38" patternUnits="userSpaceOnUse"><path d="M 38 0 L 0 0 0 38" fill="none" stroke="rgba(161,236,251,.09)" strokeWidth="1" /></pattern></defs><rect width="760" height="410" fill="url(#rover-grid)" /><path className="track-contour" d="M-20 300 C120 160 200 350 330 230 S540 110 790 180" /><path className="track-contour" d="M-20 350 C120 220 205 390 350 280 S575 180 790 250" /><path className="planned-route" d="M86 320 C180 294 240 232 330 254 S470 306 580 198 S660 120 690 86" /><path className="alternate-route" d="M86 320 C180 294 260 160 370 160 S515 144 690 86" /><path className="travelled-route" d={`M86 320 C${86 + progress * 90} ${320 - progress * 25} ${170 + progress * 120} ${294 - progress * 62} ${86 + progress * 504} ${320 - progress * 234}`} /><circle className="tracking-hazard" cx="420" cy="222" r="28" /><circle className="tracking-target" cx="690" cy="86" r="11" /><g transform={`translate(${86 + progress * 504} ${320 - progress * 234})`} className="rover-marker"><rect x="-25" y="-13" width="50" height="24" rx="3" /><rect x="-10" y="-27" width="20" height="15" /><circle cx="-18" cy="15" r="8" /><circle cx="0" cy="15" r="8" /><circle cx="18" cy="15" r="8" /><path d="M0-27 L0-39" /><circle cx="0" cy="-41" r="3" /></g><text x="24" y="38" className="map-title">ROVER POSITION / LOCAL TERRAIN FRAME</text><text x="590" y="65" className="map-label-svg">NEXT WAYPOINT</text><text x="380" y="208" className="map-label-svg hazard-label-svg">HAZARD</text></svg>;

const SatelliteVisual = ({ progress, fault }) => { const angle = progress * Math.PI * 2; const x = 380 + Math.cos(angle) * 230; const y = 205 + Math.sin(angle) * 105; return <svg className="tracking-svg" viewBox="0 0 760 410" role="img" aria-label="Simulated CubeSat in orbit"><defs><radialGradient id="planet-glow"><stop offset="0" stopColor="#294f5e" /><stop offset="1" stopColor="#07151c" /></radialGradient></defs><rect width="760" height="410" fill="#031119" /><ellipse className="orbit-path" cx="380" cy="205" rx="285" ry="135" /><ellipse className="orbit-path orbit-secondary" cx="380" cy="205" rx="220" ry="105" /><circle cx="380" cy="205" r="112" fill="url(#planet-glow)" stroke="rgba(161,236,251,.48)" /><path className="planet-line" d="M288 178 C340 150 400 170 470 140 M290 238 C340 260 420 240 478 260" /><g transform={`translate(${x} ${y})`} className={fault ? "sat-marker fault" : "sat-marker"}><rect x="-18" y="-16" width="36" height="32" rx="2" /><rect x="-39" y="-8" width="17" height="16" /><rect x="22" y="-8" width="17" height="16" /><path d="M0-16 L0-29 M0 16 L0 29" /><circle cx="0" cy="-32" r="3" /></g><text x="24" y="38" className="map-title">1U CUBESAT-STYLE DEMONSTRATOR / ORBITAL FRAME</text><text x="486" y="82" className="map-label-svg">AMINA CUBESAT</text><text x="340" y="205" className="map-label-svg">PLANETARY BODY</text>{fault && <text x="25" y="378" className="fault-label-svg">THERMAL ANOMALY / SAFE MODE RESPONSE</text>}</svg>; };

const Tracking = ({ entered, mode }) => {
  const satellite = mode === "satellite";
  const { scenario, progress, running, setRunning, setScenario } = useMission();
  const [follow, setFollow] = useState(true);
  const fault = satellite && scenario === "cubesat";
  const targetReached = progress > .9;

  return <Appear animate show={entered}><div className="tracking-page">
    <div className="tracking-hero"><div><span className="eyebrow">AMINA-LUNAR / {satellite ? "ORBITAL POSITION" : "MOBILITY TELEMETRY"}</span><h1>{satellite ? "CubeSat · Orbital View" : "Rover · Live Position"}</h1><p>{satellite ? "A software demonstrator for spacecraft autonomy, orbital telemetry, and fault recovery. No deployed satellite is implied." : "Watch the simulated rover move through terrain, update its route, and carry its mission state forward in real time."}</p></div><div className="tracking-state"><span className="live-dot" />{running ? "LIVE SIMULATION" : "SIMULATION PAUSED"}<button onClick={() => setRunning(value => !value)}>{running ? "PAUSE" : "RESUME"}</button></div></div>
    <div className="tracking-layout"><section className="tracking-map panel"><div className="tracking-heading"><span>{satellite ? "SPACECRAFT POSITION / ORBITAL VIEW" : "ROVER POSITION / TERRAIN MAP"}</span><b>{satellite ? "SIMULATED ORBIT" : "SOL 042 · LOCAL FRAME"}</b></div>{satellite ? <SatelliteVisual progress={progress} fault={fault} /> : <RoverVisual progress={progress} />}<div className="tracking-legend"><span><i className="legend-rover" />{satellite ? "CUBESAT" : "ROVER"}</span><span><i className="legend-path" />{satellite ? "ORBIT PATH" : "TRAVELLED PATH"}</span><span><i className="legend-target" />{satellite ? "GROUND LINK" : "CURRENT TARGET"}</span><span><i className="legend-hazard" />{satellite ? "FDIR STATE" : "HAZARD"}</span></div></section>
      <aside className="tracking-side"><section className="panel status-panel"><div className="tracking-heading"><span>{satellite ? "SPACECRAFT STATUS" : "ROVER STATUS"}</span><b className={fault ? "fault-text" : "good-text"}>{fault ? "SAFE MODE" : "NOMINAL"}</b></div>{satellite ? <><div className="tracking-stat"><span>POSITION</span><strong>142.8° E / 18.4° N</strong></div><div className="tracking-stat"><span>ALTITUDE / VELOCITY</span><strong>412 km · 7.66 km/s</strong></div><div className="tracking-stat"><span>POWER / THERMAL</span><strong>{fault ? "87% · ANOMALY" : "87% · NORMAL"}</strong></div><div className="tracking-stat"><span>MISSION MODE</span><strong>{fault ? "SAFE MODE" : "SCIENCE"}</strong></div><button className={fault ? "fault-button active" : "fault-button"} onClick={() => setScenario(fault ? "normal" : "cubesat")}>{fault ? "CLEAR THERMAL FAULT" : "TRIGGER THERMAL ANOMALY"}</button></> : <><div className="tracking-stat"><span>POSITION / HEADING</span><strong>X 14.2 / Y 32.8 · 127°</strong></div><div className="tracking-stat"><span>SPEED / DISTANCE</span><strong>0.18 m/s · 342 m</strong></div><div className="tracking-stat"><span>CURRENT TARGET</span><strong>T-04 · HYDRATED VEIN</strong></div><div className="tracking-stat"><span>MISSION MODE</span><strong>{progress > .9 ? "TARGET REACHED" : "EXPLORING"}</strong></div><button className={follow ? "follow-button active" : "follow-button"} onClick={() => setFollow(value => !value)}>{follow ? "FOLLOWING ROVER" : "FOLLOW ROVER"}</button></>}</section>
        <section className="panel tracking-events"><div className="tracking-heading"><span>LIVE TRACKING TIMELINE</span><b>STREAMING</b></div>{(satellite ? satelliteEvents : roverEvents).map(([time, event, type]) => <div className="tracking-event" key={time}><time>{time}</time><span>{type}</span><b>{event}</b></div>)}</section></aside></div>
      {!satellite && <section className="panel science-capture-panel"><div className="capture-heading"><div><span className="capture-pin">●</span><strong>{targetReached ? "TARGET REACHED" : "TARGET APPROACH"}</strong><small>{targetReached ? "Captured 6 science images at Target #07" : "Science capture queued for Target #07"}</small></div><b>{targetReached ? "SCIENCE CAPTURED" : "CAPTURE QUEUED"}</b></div><div className="capture-content"><div className="capture-grid">{scienceFrames.map(([source, name, label], index) => <div className={`science-frame frame-${index + 1}`} key={source}><span>{index + 1}</span><img src={source} alt={label} /><b>{name}</b><small>{label}</small></div>)}</div><div className="capture-summary"><b>TARGET #07</b><span>SCIENCE VALUE</span><strong>87%</strong><span>PRIORITY</span><strong>HIGH</strong><span>IMAGES {targetReached ? "CAPTURED" : "QUEUED"}</span><strong>{targetReached ? "6/6" : "READY"}</strong></div></div></section>}
  </div></Appear>;
};

export default Tracking;
